name: Build and Deploy

on:
  push:
    branches:
      - master
    path-ignore:
      - README.md
      - LICENSE

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12.16.1"
      
      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_TOKEN }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "./build/*"
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          TARGET: "/home/timestamp-converter"